---
title: "Homework3"
author: "Sparhawk"
date: "2023-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 1. 

To turn an Excel type data frame such as

```
First String    Second      1.22      3.4
Second          More Text   1.555555  2.2220
Third           x           3         124 
```

into a .csv format like this

```
First String,Second,1.22,3.4
Second,More Text,1.555555,2.2220
Third,x,3,124
```

you can use this regular expression:
```
Find: "  \s+" (there's a space first)

Replace: " , "
```
This simply replaces all of the spaces and tabs of any length greater than one with a single comma. Line breaks are left untouched.

### Question 2

Turn this
```
Ballif, Bryan, University of Vermont
Ellison, Aaron, Harvard Forest
Record, Sydne, Bryn Mawr
```
into this
```
Bryan Ballif (University of Vermont)
Aaron Ellison (Harvard Forest)
Sydne Record (Bryn Mawr)
```
by using
```
Find: " (\w+), (\w+), (.+) "
Replace: " \2 \1 \(\3\) "
```
We can rearrange the words by capturing them. We have to escape the parentheses by backslashing before them

### Question 3
Turn this
```
0001 Georgia Horseshoe.mp3 0002 Billy In The Lowground.mp3 0003 Winder Slide.mp3 0004 Walking Cane.mp3
```
into this
```
0001 Georgia Horseshoe.mp3
0002 Billy In The Lowground.mp3
0003 Winder Slide.mp3
0004 Walking Cane.mp3
```
by using
```
Find: " .mp3  " (there's a space after the mp3)
Replace: " .mp3\n "
```
We can search for every mp3 file and replace the space after it with a line break.

### Question 4

Turn the result of question 3 into
```
Georgia Horseshoe_0001.mp3
Billy In The Lowground_0002.mp3
Winder Slide_0003.mp3
Walking Cane_0004.mp3
```
by using
```
Find: " (\d\d\d\d) (.+)\.mp3 "
Replace: " \2_\1\.mp3 "
```
This captures the initial numbers and the name of the song, and reorders them. I tried to do this without doing part 3 but it was much harder than simply doing two regular expressions (3 then 4).

### Question 5

Turn this data frame
```
Camponotus,pennsylvanicus,10.2,44
Camponotus,herculeanus,10.5,3
Myrmica,punctiventris,12.2,4
Lasius,neoniger,3.3,55
```
into this
```
C_pennsylvanicus,44
C_herculeanus,3
M_punctiventris,4
L_neoniger,55
```
using only one regular expression. This is possible with
```
Find: " (\w)\w+,(\w+),.+,(\d+) "
Replace: " \1_\2,\3 "
```
This captures only the first letter of the genus, and ignores the first numbers for capture, then is reordered to the new format.

### Question 6

Turn the original data of Question 5 into this
```
C_penn,44
C_herc,3
M_punc,4
L_neon,55
```
by using
```
Find: " (\w)\w+,(\w\w\w\w)\w+,.+,(\d+) "
Replace: " \1_\2,\3 "
```
This variant captures only the first 4 letters of the species name.

### QUestion 7

Transform the original dataset for question 5 into
```
Campen, 44, 10.2
Camher, 3, 10.5
Myrpun, 4, 12.2
Lasneo, 55, 3.3
```
by using
```
Find: " (\w\w\w)\w+,(\w\w\w)\w+,(.+),(\d+) "
Replace: " \1\2, \4, \3 "
```
This variant captures the first 3 letters of both words, and reorders the captured numbers and adds spaces.