---
title: "Homework 5"
author: "Sparhawk"
date: "2023-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Homework 5

## Question the First

Assign to the variable n_dims a single random integer between 3 and 10.
```
n_dims <- sample(seq(from=3,to=10),1)
typeof(n_dims)
```

Create a vector of consecutive integers from 1 to n_dims2
```
vec1 <- seq(from=1,to=n_dims^2)
```
Use the sample function to randomly reshuffle these values.
```
samp1 <- sample(vec1,length(vec1), replace=FALSE)
```
create a square matrix with these elements.
```
mat1 <- matrix(samp1,n_dims)
```
find a function in r to transpose the matrix. Print it to see changes.
```
matTrans <- t(mat1)
print(matTrans)
```
calculate the sum and the mean of the elements in the first row and then the last row.
```
sum1row <- sum(mat1[1,])
mean1row <- mean(mat1[1,])

sumLastrow <- sum(mat1[n_dims,])
meanLastrow <- mean(mat1[n_dims,])
```
read about the eigen() function and use it on your matrix
```
eigen(mat1)
```
For eigen values it outputs n_dims worth of irrational (looking) numbers with no apparent bounds. The first half are all different with no complex component, while the second half are pairs with + and - complex components.

For eigen vectors, it outputs a n_dims by n_dims square matrix full of complex numbers with non-imaginary components between -1 and 1.
```
typeof(eigen(mat1)$values)
typeof(eigen(mat1)$vectors)
```
The code above shows the outputs are indeed complex.

This is reproducible with another n_dims value.
```
n_dims <- sample(seq(from=3,to=10),1)

vec1 <- seq(from=1,to=n_dims^2)

samp1 <- sample(vec1,length(vec1), replace=FALSE)

mat1 <- matrix(samp1,n_dims)

matTrans <- t(mat1)

sum1row <- sum(mat1[1,])
mean1row <- mean(mat1[1,])

sumLastrow <- sum(mat1[n_dims,])
meanLastrow <- mean(mat1[n_dims,])

eigen(mat1)
```



## Question the Second

Create a list with the following named elements:

`my_matrix`, which is a 4 x 4 matrix filled with random uniform values
```
my_matrix <- matrix(runif(16, min=-1, max=1),nrow=4, ncol=4)
```
`my_logical` which is a 100-element vector of TRUE or FALSE values. Do this efficiently by setting up a vector of random values and then applying an inequality to it.
```
fuel <- runif(100,min=0,max=1)
octaneFuel <- fuel>0.5
my_logical <- matrix(octaneFuel,nrow=10,ncol=10)
```
(I can do this without the extra "octaneFuel" definition step, but I prefer this)

`my_letters`, which is a 26-element vector of all the lower-case letters in random order.
```
my_letters <- sample(letters,size=length(letters),replace=FALSE)
```

Now complete the followign steps:



create a new list, which has the element[2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector.
```
my_list <- c(my_matrix[2,2], my_logical[1,2], my_letters[2])
```
use the typeof() function to confirm the underlying data types of each component in this list
```
typeof(my_list[[1]])
typeof(my_list[[2]])
typeof(my_list[[3]])
summary(my_list)
```
combine the underlying elements from the new list into a single atomic vector with the c() function.
```
my_list2 <- c(my_matrix[2,2], my_logical[1,2], my_letters[2])
```
the data type of THIS vector is all "character"



## Question the Third and Final!

Create a data frame with the two variables (= columns) and 26 cases (= rows) below:


call the first variable my_unis and fill it with 26 random uniform values from 0 to 10
```
my_unis <- runif(26,min=0,max=10)
```
call the second variable my_letters and fill it with 26 capital letters in random order.
```
my_letters <- sample(LETTERS,size=length(LETTERS), replace=FALSE)
```
Now create the data frame:
```
my_frame <- data.frame(my_unis,my_letters)
```
for the first variable, use a single line of code in R to select 4 random rows and replace the numerical values in those rows with NA.
```
my_frame[sample(seq(from=1,to=nrow(my_frame)),4),1] <- NA
```
for the first variable, write a single line of R code to identify which rows have the missing values.
```
which(!complete.cases(my_frame[,1]))
```
re-order the entire data frame to arrange the second variable in alphabetical order
```
alphabetical <- order(my_frame[,2])
my_frame2 <- my_frame[alphabetical,]
```
calculate the column mean for the first variable.
```
mean(my_frame2[,1],na.rm = TRUE)
```
et voila.